#
# Executes commands at login pre-zshrc.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

#
# Browser
#

if [[ "$OSTYPE" == darwin* ]]; then
  export BROWSER='open'
fi

#
# Editors
#

export EDITOR='vim'
export VISUAL='vim'
export PAGER='less'

#
# Language
#

if [[ -z "$LANG" ]]; then
    if [[ "$TERM" == "xterm*" ]]; then
	export LANG='zh_CN.UTF-8'
    else
	export LANG='en_US.UTF-8'
    fi
fi

#
# Paths
#

# Ensure path arrays do not contain duplicates.
typeset -gU cdpath fpath mailpath path

# Set the list of directories that cd searches.
# cdpath=(
#   $cdpath
# )

# Set the list of directories that Zsh searches for programs.
_altpath=(
  $HOME/.dotfiles/{bin,sbin}
  $HOME/.ssh/usm
  $HOME/.cargo/bin
  $HOME/Work/Local/{bin,sbin}
  $HOME/.local/{bin,sbin}
  $HOME/.{bin,sbin}
  $HOME/{bin,sbin}
  $HOME/.mix/escripts
  /opt/homebrew/bin
  /opt/elixir/bin
  /opt/erl/bin
  /usr/local/{bin,sbin}
  /usr/{bin,sbin}
  /{bin,sbin}
)
altpath=()

for p in ${_altpath[@]}; do
    [ -d "$p" ] && altpath=($altpath $p)
done

path=(
  $altpath
  $path
)

#
# Less
#

# Set the default Less options.
# Mouse-wheel scrolling has been disabled by -X (disable screen clearing).
# Remove -X and -F (exit if the content fits on one screen) to enable it.
export LESS='-F -g -i -M -R -S -w -X -z-4'

# Set the Less input preprocessor.
# Try both `lesspipe` and `lesspipe.sh` as either might exist on a system.
if (( $#commands[(i)lesspipe(|.sh)] )); then
  export LESSOPEN="| /usr/bin/env $commands[(i)lesspipe(|.sh)] %s 2>&-"
fi

[ -e "$HOME/.zprofile.user" ] && source "$HOME/.zprofile.user"

(( $+commands[luarocks] )) && eval "$(luarocks path)"



# Added by OrbStack: command-line tools and integration
# This won't be added again if you remove it.
source ~/.orbstack/shell/init.zsh 2>/dev/null || :
