#
# Defines environment variables.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Ensure that a non-login, non-interactive shell has a defined environment.
if [[ ( "$SHLVL" -eq 1 && ! -o LOGIN ) && -s "${ZDOTDIR:-$HOME}/.zprofile" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprofile"
fi

export TGC=1
export GOPATH=$HOME/Work/Local
# export MANPATH="/usr/local/man:$MANPATH"
#export all_proxy=socks5://localhost:1080
#export http_proxy=socks5://localhost:1080
#export https_proxy=socks5://localhost:1080

export C_INCLUDE_PATH="$HOME/Work/Local/include"
export CPLUS_INCLUDE_PATH="$HOME/Work/Local/include"

export LIBRARY_PATH="$HOME/Work/Local/lib"
export LD_LIBRARY_PATH="$HOME/Work/Local/lib"
export DYLD_LIBRARY_PATH="$HOME/Work/Local/lib"
export LD_LIBRARY_PATHS="$HOME/Work/Local/lib"

export LUA_PATH_5_3="./?.lua;./?/init.lua;;"
export LUA_CPATH_5_3="./?.so;./loadall.so;;"

PERL5LIB="/Users/starwing/perl5/lib/perl5${PERL5LIB:+:${PERL5LIB}}"; export PERL5LIB;
PERL_LOCAL_LIB_ROOT="/Users/starwing/perl5${PERL_LOCAL_LIB_ROOT:+:${PERL_LOCAL_LIB_ROOT}}"; export PERL_LOCAL_LIB_ROOT;
PERL_MB_OPT="--install_base \"/Users/starwing/perl5\""; export PERL_MB_OPT;
PERL_MM_OPT="INSTALL_BASE=/Users/starwing/perl5"; export PERL_MM_OPT;

#export HOMEBREW_BOTTLE_DOMAIN="https://mirrors.tuna.tsinghua.edu.cn/homebrew-bottles"
export HOMEBREW_BOTTLE_DOMAIN=https://mirrors.ustc.edu.cn/homebrew-bottles

#export RUSTUP_DIST_SERVER=https://mirrors.tuna.tsinghua.edu.cn/rustup

(( $+commands[fd] )) && export FZF_DEFAULT_COMMAND='fd --type f'
export FZF_DEFAULT_OPTS="--height=30% --layout=reverse --inline-info"

export GIT_EDITOR=vim
export ERL_AFLAGS="-kernel shell_history enabled"

#export HEX_MIRROR="https://hexpm.upyun.com"
#export HEX_CDN="https://hexpm.upyun.com"

#[ -e "$HOME/.asdf/asdf.sh" ] && source $HOME/.asdf/asdf.sh
[ -e "$HOME/.zshenv.user" ] && source $HOME/.zshenv.user

export HOMEBREW_NO_AUTO_UPDATE=1

source "$HOME/.cargo/env"
. "$HOME/.cargo/env"
